#!/bin/bash

trbcmd reload 0x1482
sleep 3
./addresses.sh
# set trigger to cts
trbcmd w 0x1482 0xcf00 0x100
# set data limit
trbcmd w 0x1482 0xc804 100
# set trigger windows +- 250 ns
#trbcmd w 0x1482 0xc801 0x80320032
# set trigger windews -100 ns to +500 ns
trbcmd w 0x1482 0xc801 0x80640014
# disable trigger windows, e.g. for Fe55 scan
#trbcmd w 0x1482 0xc801 0x17600010


# enable relevant TDC channels
#trbcmd w 0x1482 0xc802 0x00ff01bf ## if PT board 2 is connected to ch 0-7
#trbcmd w 0x1482 0xc802 0x00ff01ff ## if PT board 1 is connected to ch 0-7

# only read out ch 0-7 + trigger
trbcmd w 0x1482 0xc802 0x000001ff ## if PT board 1 is connected to ch 0-7
#disable asd8 data out
trbcmd w 0x1483 0xc802 0x00000000 

./init_asics
