#!/bin/bash

trbcmd reload 0x1483
sleep 3
./addresses.sh
# set trigger to cts
trbcmd w 0x1483 0xcf00 0x100
# set data limit
trbcmd w 0x1483 0xc804 100
# set trigger windows +- 250 ns
trbcmd w 0x1483 0xc801 0x80320032
# enable relevant TDC channels
trbcmd w 0x1483 0xc802 0x00ff01ff
