#!/bin/bash

#$1 defines interface
#$2 defines chip on board
#$3 defines threshold


chip=$2
thresh=$3


if [ $chip == "0" ]; then
trbcmd w 0x1482 0xa000 "0x523"$(printf "%02x" $thresh)
elif [ $chip == "1" ]; then
trbcmd w 0x1482 0xa000 "0x543"$(printf "%02x" $thresh)
else
echo "invalid chip number, usage: ./threshold <chip> <thresh>"
echo " chip = 0|1, thresh = 0-127"
fi
