#!/bin/bash


stty -F /dev/ttyUSB_stage_pollux_house speed 19200
sleep 0.1
pos=$(printf "%0.0f" $(echo "scale=2; $1 * 1000000" | bc -l))
echo " $pos 4 nmove" > /dev/ttyUSB_stage_pollux_house
sleep 0.1
